### ISSUE TITLE
Code structure

### ISSUE THREAD

**Issue by MahmoudYounes** [mr-eyes/duplicate_images_detector#1]
Hi, this is just a suggestion, why not you modularize the main module to be efficient and make it possible to use it as an out of the box library? maybe you can even provide a setup.py and create a library out of this app.

I would be glad to work on this if contribution is welcome.

**Comment by mr-eyes** [comment]
@MahmoudYounes Sure, you can make the edits you want and then discuss for merging your updates.
Also, it was just for my personal use, Contributions are more than welcome.
